{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "talentmap.name" . }}-backend-uploads-pvc
  namespace: {{ include "talentmap.namespace" . }}
  labels:
    {{- include "talentmap.backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
