apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ include "talentmap.namespace" . }}
  labels:
    {{- include "talentmap.backend.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ include "talentmap.name" . }}-postgres"
  DB_PORT: "{{ .Values.postgres.service.port }}"
  DB_NAME: "{{ .Values.postgres.database }}"
  DB_USER: "{{ .Values.postgres.username }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.backend.config.corsAllowedOrigins }}"
  JWT_VALIDITY: "{{ .Values.backend.config.jwtValidity }}"
