apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ include "talentmap.namespace" . }}
  labels:
    {{- include "talentmap.frontend.labels" . | nindent 4 }}
data:
  VITE_API_BASE_URL: "{{ .Values.frontend.config.apiUrl }}"
